export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const PLAN_SUCCESS = 'PLAN_SUCCESS';
export const PLAN_FAIL = 'PLAN_FAIL';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export const ADD_CHECKOUT_ITEM = 'ADD_CHECKOUT_ITEM';
export const REMOVE_CHECKOUT_ITEM = 'REMOVE_CHECKOUT_ITEM';